# Generated by Django 3.2.5 on 2021-08-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
