# Generated by Django 3.2.5 on 2021-08-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='category_id',
            new_name='category',
        ),
    ]
