# Generated by Django 3.2.5 on 2021-08-26 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210826_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.CharField(default='ABC', max_length=100),
        ),
        migrations.AddField(
            model_name='listings',
            name='starting_price',
            field=models.IntegerField(default='123'),
        ),
        migrations.AddField(
            model_name='listings',
            name='title',
            field=models.CharField(default='ABC', max_length=50),
        ),
        migrations.AddField(
            model_name='listings',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
