# Generated by Django 3.2.5 on 2021-08-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210826_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='user_id',
            new_name='user',
        ),
    ]
