# Generated by Django 3.2.5 on 2021-09-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210826_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
